### PR TITLE
1.6.1

### PR DESCRIPTION
**Pull request by WillDaSilva**
- Replaced `toml` with `tomli`.
- Updated requirement version constraints to match `flit_scm`.

### CODE REVIEW

**Comment by WillDaSilva** [comment]
Recreated PR https://github.com/conda-forge/flit-scm-feedstock/pull/4, this time using a personal fork as per @conda-forge-linter's instructions.

**Review by xylar — APPROVED** [review]
Looks good!  Merge when you're ready.

**Comment by xylar** [comment]
Oops, didn't see that tests are failing.  Don't merge yet...

**Comment by WillDaSilva** [comment]
Just fixed the tests in 1.6.2 - new PR will be up shortly

**Pull request closed without merging**
